# Generated by Django 5.1.1 on 2025-06-17 02:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descri',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
