# Generated by Django 5.1.1 on 2025-06-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_descri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='descri',
            field=models.TextField(blank=True, null=True),
        ),
    ]
