# Generated by Django 5.1.1 on 2025-06-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_descri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descri',
            new_name='Noticia',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
