# Generated by Django 5.1.1 on 2025-06-17 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
